### ISSUE TITLE
Crating Table bug you dont cant craft anything

### ISSUE THREAD

**Issue by DragonfireHD** [SkylineMC/Mockingbird#11]
This Plugin have a CraftingTable bug only this plugin have that
can you fix this invsee is keep going

**Comment by DragonfireHD** [comment]
Video

**Comment by ethaniccc** [comment]
Could you give reproduction steps on how to produce this bug, or a video of the bug?

**Comment by DragonfireHD** [comment]
Yes i but here the link

**Comment by DragonfireHD** [comment]
Look on the fance and Sticks in the Video

**Comment by DragonfireHD** [comment]
https://youtu.be/ywDRq35MkrE

**Comment by ethaniccc** [comment]
Fix in latest dev build: https://poggit.pmmp.io/r/96104/Mockingbird_dev-99.phar
